  - name: "Check if url variable exists"
    fail: msg="Bailing out. You are required to set the url." 
    when: url is not defined

  - name: Download port_check.py 
    get_url: 
      url: https://raw.githubusercontent.com/racker/rackspace-monitoring-agent-plugins-contrib/master/multi_curl_check.sh
      dest: /usr/lib/rackspace-monitoring-agent/plugins/multi_curl_check.sh
      mode: 0744
      owner: root
      group: root
    notify: restart rackspace-monitoring-agent

  - name: Copy multi_curl_check.yaml
    template: src=multi_curl_check.yaml.j2 dest=/etc/rackspace-monitoring-agent.conf.d/multi_curl_{{url}}.yaml
    notify: restart rackspace-monitoring-agent
