  - name: Download mutli_curl_check.sh
    get_url: 
      url: https://raw.githubusercontent.com/tbr0/cloud-monitoring-plugin-deploy/master/resources/multi_curl_check.sh
      dest: /usr/lib/rackspace-monitoring-agent/plugins/multi_curl_check.sh
      mode: 0744
      owner: root
      group: root
    notify: restart rackspace-monitoring-agent

  - name: Copy multi_curl_check.yaml
    template: src=multi_curl_check.yaml.j2 dest=/etc/rackspace-monitoring-agent.conf.d/multi_curl_{{url}}.yaml
    notify: restart rackspace-monitoring-agent
